name: node_app

on:
  push:
    branches:
      -"main"

jobs:
  build:
    name: Buils Docker image
    runs-on: ubuntu-latest
    steps:
    - # Клон приложения в ОС
      name: Checkout
      uses: actions/checkout@v3
    - # Вход в DockerHub
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_TOKEN}}
    - # Создание экземпляра build kit builder
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_TOKEN}}/clockbox:latest
